// 本文件由 unplugin-auto-import 维护并提交到仓库，用于让 TypeScript 识别自动导入标识符；生成文件豁免 L3 头部。
export {}

declare global {
  const useState: typeof import('react')['useState']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useCallback: typeof import('react')['useCallback']
  const useRef: typeof import('react')['useRef']

  const AlertDialog: typeof import('./components/ui/alert-dialog')['AlertDialog']
  const AlertDialogAction: typeof import('./components/ui/alert-dialog')['AlertDialogAction']
  const AlertDialogCancel: typeof import('./components/ui/alert-dialog')['AlertDialogCancel']
  const AlertDialogContent: typeof import('./components/ui/alert-dialog')['AlertDialogContent']
  const AlertDialogDescription: typeof import('./components/ui/alert-dialog')['AlertDialogDescription']
  const AlertDialogFooter: typeof import('./components/ui/alert-dialog')['AlertDialogFooter']
  const AlertDialogHeader: typeof import('./components/ui/alert-dialog')['AlertDialogHeader']
  const AlertDialogTitle: typeof import('./components/ui/alert-dialog')['AlertDialogTitle']
  const AlertDialogTrigger: typeof import('./components/ui/alert-dialog')['AlertDialogTrigger']
  const Badge: typeof import('./components/ui/badge')['Badge']
  const Button: typeof import('./components/ui/button')['Button']
  const Card: typeof import('./components/ui/card')['Card']
  const CardContent: typeof import('./components/ui/card')['CardContent']
  const CardDescription: typeof import('./components/ui/card')['CardDescription']
  const CardHeader: typeof import('./components/ui/card')['CardHeader']
  const CardTitle: typeof import('./components/ui/card')['CardTitle']
  const Dialog: typeof import('./components/ui/dialog')['Dialog']
  const DialogContent: typeof import('./components/ui/dialog')['DialogContent']
  const DialogDescription: typeof import('./components/ui/dialog')['DialogDescription']
  const DialogFooter: typeof import('./components/ui/dialog')['DialogFooter']
  const DialogHeader: typeof import('./components/ui/dialog')['DialogHeader']
  const DialogTitle: typeof import('./components/ui/dialog')['DialogTitle']
  const Input: typeof import('./components/ui/input')['Input']
  const Label: typeof import('./components/ui/label')['Label']
  const Select: typeof import('./components/ui/select')['Select']
  const SelectContent: typeof import('./components/ui/select')['SelectContent']
  const SelectGroup: typeof import('./components/ui/select')['SelectGroup']
  const SelectItem: typeof import('./components/ui/select')['SelectItem']
  const SelectLabel: typeof import('./components/ui/select')['SelectLabel']
  const SelectScrollDownButton: typeof import('./components/ui/select')['SelectScrollDownButton']
  const SelectScrollUpButton: typeof import('./components/ui/select')['SelectScrollUpButton']
  const SelectSeparator: typeof import('./components/ui/select')['SelectSeparator']
  const SelectTrigger: typeof import('./components/ui/select')['SelectTrigger']
  const SelectValue: typeof import('./components/ui/select')['SelectValue']
  const Table: typeof import('./components/ui/table')['Table']
  const TableBody: typeof import('./components/ui/table')['TableBody']
  const TableCell: typeof import('./components/ui/table')['TableCell']
  const TableHead: typeof import('./components/ui/table')['TableHead']
  const TableHeader: typeof import('./components/ui/table')['TableHeader']
  const TableRow: typeof import('./components/ui/table')['TableRow']

  const IconLucideActivity: typeof import('~icons/lucide/activity')['default']
  const IconLucideChartBar: typeof import('~icons/lucide/chart-bar')['default']
  const IconLucideChevronLeft: typeof import('~icons/lucide/chevron-left')['default']
  const IconLucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
  const IconLucideDatabase: typeof import('~icons/lucide/database')['default']
  const IconLucideLayoutDashboard: typeof import('~icons/lucide/layout-dashboard')['default']
  const IconLucidePencil: typeof import('~icons/lucide/pencil')['default']
  const IconLucidePlus: typeof import('~icons/lucide/plus')['default']
  const IconLucideSearch: typeof import('~icons/lucide/search')['default']
  const IconLucideShieldCheck: typeof import('~icons/lucide/shield-check')['default']
  const IconLucideTrash2: typeof import('~icons/lucide/trash-2')['default']
  const IconLucideTriangleAlert: typeof import('~icons/lucide/triangle-alert')['default']
  const IconLucideUsers: typeof import('~icons/lucide/users')['default']
  const IconLucideX: typeof import('~icons/lucide/x')['default']

  const useBoolean: typeof import('./hooks/useBoolean')['useBoolean']
  const useCrud: typeof import('./hooks/useCrud')['useCrud']
}
